services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2G
        reservations:
          cpus: '0.2'
          memory: 1G
    restart: unless-stopped
    ports:
      - "8080:8080"  # Jenkins Web Interface
      - "50000:50000"  # Jenkins Agent Communication
    volumes:
      - ${JENKINS_HOME}:/var/jenkins_home
    extra_hosts:
      - "jenkins.test:192.117.0.2" # to nginx
    environment:
      - JENKINS_ARGS="--prefix=/jenkins --httpsPort=-1 --httpPort=8080"
    networks:
      dev_host:
        ipv4_address: 192.117.0.8

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '8880:8880'  #portfolio webpack
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ${PROJECT_FILES}:/project_files
      - ./nginx/template-variables:/etc/nginx/templates/10-variables.conf.template:ro
      - ${JENKINS_HOME}:/var/jenkins_home
    environment:
      - PORTFOLIO_DIR
      - PROJECT_FILES
    networks:
      dev_host:
        ipv4_address: 192.117.0.2

  portfolio:
    build:
      context: docker/php-8.3-fpm
      dockerfile: Dockerfile
      args:
        - RUNNING_USER=${RUNNING_USER}
        - RUNNING_GROUP=${RUNNING_GROUP}
    container_name: portfolio
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PROJECT_FILES}:/project_files
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php/pool.conf:/usr/local/etc/pool.conf
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./php/supervisor_conf_d:/etc/supervisor/conf.d
    extra_hosts:
        - "portfolio.test:192.117.0.2" # to nginx
    networks:
      dev_host:
        ipv4_address: 192.117.0.6

  postgres:
    image: "${POSTGRES_IMAGE}"
    restart: always
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - "${POSTGRES_DATA_DIR}:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PW}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_DB=${POSTGRES_DB}"
#    extra_hosts:
#      - "localhost:127.0.0.1"
    networks:
      dev_host:
        ipv4_address: 192.117.0.7

  # redis:
  #   container_name: redis
  #   image: redis
  #   hostname: redis
  #   restart: always
  #   command: ["redis-server", "--appendonly", "yes"]
  #   networks:
  #     dev_host:
  #       ipv4_address: 192.117.0.
  #
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    restart: always
    volumes:
      - ${PGADMIN_CONF_DIR}:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
    networks:
      dev_host:
        ipv4_address: 192.117.0.4

  mailcatcher:
    container_name: mailcatcher
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: always
    networks:
      dev_host:
        ipv4_address: 192.117.0.3

networks:
  dev_host:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  192.117.0.0/16
